const data={
    products:[
        {
            name:'Nike Slim Shirt',
            slug:'nike-slim-shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Adidas Slim Shirt',
            slug:'Adidas-slim-shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:250,
            countInStock:20,
            brand:'Adidas',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Lacoste Slim Shirt',
            slug:'Lacoste-slim-shirt',
            category:'Shirts',
            image:'/images/p4.jpg',
            price:220,
            countInStock:0,
            brand:'Lacoste',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            name:'Nike Slim Pant',
            slug:'Nike-slim-pant',
            category:'Pants',
            image:'/images/p3.jpg',
            price:78,
            countInStock:15,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
    ]
};
export default data;
